compatibility_date = "2022-05-31"
name = "durable-object-demo"
type = "javascript"
account_id = ""
workers_dev = true

[build]
command = "npm run build:api"
[build.upload]
format = "modules"
dir = "dist"
main = "index.mjs"

[durable_objects]
bindings = [
	{ name = "counter", class_name = "Counter" },
]

[env.wrangler]
durable_objects.bindings = [
	{ name = "counter", class_name = "Counter" },
]

[[migrations]]
tag = "v1"
new_classes = ["Counter"]

[miniflare]
durable_objects_persist = "./.miniflare/durable-objects/"
kv_persist = "./.miniflare/kv/"